security:
  oauth2:
    client:
      clientId: 8d44da36-b675-4ce0-8e02-9f19dd6b1f0d
      clientSecret: 76aac839-6435-4868-b94f-a2574212f1f5
      accessTokenUri: https://ssotest.login.system.dev.east.paas.geointservices.io/oauth/token
      userAuthorizationUri: https://ssotest.login.system.dev.east.paas.geointservices.io/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://ssotest.login.system.dev.east.paas.geointservices.io/userinfo