spring:
  datasource:
    url: ${FRITZ_DB_URL}
    username: ${FRITZ_DB_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
    out-of-order: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: create-drop
      use-new-id-generator-mappings: false
  servlet:
    multipart:
      max-file-size: 100MB

server.compression.enabled: false